#!/usr/bin/env python3
"""One-shot generator for secondary_keywords.py.

Reads V5.py:INDUSTRY_KEYWORDS, queries SEMrush per-industry anchor keywords
via the phrase_related endpoint, filters to CPC > 0.05 and volume > 0,
excludes any phrase already present anywhere in the primary dict
(case-insensitive), and writes the top 30 per industry to
secondary_keywords.py — overwriting whatever was there.

Run from the project folder:

    SEMRUSH_API_KEY=... python generate_secondary_keywords.py
    # or with a region override:
    SEMRUSH_DB=au python generate_secondary_keywords.py

Cost note: one SEMrush phrase_related call = ~10 credits. This script fires
up to 3 calls per industry (3 anchors) × ~25 industries ≈ 750 credits total
for a full seed. Run once and commit the output file.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

# Local imports — project root must be on sys.path already
sys.path.insert(0, str(Path(__file__).resolve().parent))

from V5 import INDUSTRY_KEYWORDS, SemrushClient, API_KEYS  # noqa: E402

log = logging.getLogger("generate_secondary_keywords")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

# Tunables
ANCHORS_PER_INDUSTRY = 3        # how many primary keywords to expand per industry
RAW_PER_ANCHOR = 30             # fetch up to this many raw phrase_related results per anchor
MIN_CPC = 0.05                  # user-confirmed threshold
MIN_VOLUME = 1                  # any non-zero volume is acceptable
TARGET_PER_INDUSTRY = 30        # final count after filtering + ranking
SLEEP_BETWEEN_ANCHORS_SEC = 0.4 # politeness: small gap between SEMrush calls


def _primary_phrase_universe(primary: Dict[str, List[str]]) -> set[str]:
    """Case-insensitive set of every keyword in the primary dict, any industry."""
    out: set[str] = set()
    for kws in primary.values():
        for kw in kws:
            if kw:
                out.add(kw.strip().lower())
    return out


def _fetch_one_industry(
    industry: str,
    anchors: List[str],
    semrush: SemrushClient,
    database: str,
    excluded: set[str],
) -> List[Tuple[str, int, float]]:
    """Fetch + filter secondary candidates for a single industry.
    Returns list of (keyword, volume, cpc) sorted by value desc."""
    seen_in_industry: set[str] = set()
    candidates: List[Tuple[str, int, float]] = []

    for anchor in anchors[:ANCHORS_PER_INDUSTRY]:
        if not anchor:
            continue
        try:
            raw = semrush.get_related_keywords(anchor, database=database, display_limit=RAW_PER_ANCHOR)
        except Exception as e:
            log.warning("   anchor=%r fetch failed: %s", anchor, e)
            raw = []
        log.info("   anchor=%r returned %d raw kws", anchor, len(raw))
        for r in raw:
            kw = (r.get("keyword") or "").strip()
            vol = int(r.get("volume") or 0)
            cpc = float(r.get("cpc") or 0.0)
            key = kw.lower()
            if not kw:
                continue
            if key in excluded:
                continue
            if key in seen_in_industry:
                continue
            if vol < MIN_VOLUME or cpc <= MIN_CPC:
                continue
            seen_in_industry.add(key)
            candidates.append((kw, vol, cpc))
        time.sleep(SLEEP_BETWEEN_ANCHORS_SEC)

    # Rank by volume * cpc — reflects both search demand and commercial value
    candidates.sort(key=lambda t: (t[1] * t[2], t[1]), reverse=True)
    return candidates[:TARGET_PER_INDUSTRY]


def _render_output(
    result: Dict[str, List[str]],
    database: str,
    stats: Dict[str, Dict[str, int]],
) -> str:
    """Produce the full secondary_keywords.py file text."""
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    header = f'''"""Secondary keyword dictionary — NON-OVERLAPPING with V5.py:INDUSTRY_KEYWORDS.

Auto-generated by generate_secondary_keywords.py on {generated_at}.
SEMrush database: {database!r}
Filter: CPC > {MIN_CPC}, volume ≥ {MIN_VOLUME}.
Rank: volume * cpc (desc), top {TARGET_PER_INDUSTRY} per industry.

Stats per industry (kept_count / raw_candidates):
'''
    stat_lines = []
    for ind in sorted(stats):
        s = stats[ind]
        stat_lines.append(f"  {ind!r}: kept={s['kept']}, raw={s['raw']}")
    stat_block = "\n".join(stat_lines)
    tail = '''
Do not edit by hand — re-run the generator to refresh.
"""
from __future__ import annotations

from typing import Dict, List

'''
    data_lit = "SECONDARY_INDUSTRY_KEYWORDS: Dict[str, List[str]] = {\n"
    for industry in sorted(result):
        kws = result[industry]
        data_lit += f"    {industry!r}: [\n"
        for kw in kws:
            data_lit += f"        {kw!r},\n"
        data_lit += "    ],\n"
    data_lit += "}\n"

    footer = f'''
GENERATED_AT: str = {generated_at!r}
GENERATED_WITH_DB: str = {database!r}
GENERATOR_VERSION: str = "1.0.0"


def has_keywords_for(industry: str) -> bool:
    return bool(SECONDARY_INDUSTRY_KEYWORDS.get(industry))


def get_keywords(industry: str) -> List[str]:
    return list(SECONDARY_INDUSTRY_KEYWORDS.get(industry, []))
'''
    return header + stat_block + tail + data_lit + footer


def main() -> int:
    api_key = os.environ.get("SEMRUSH_API_KEY") or API_KEYS.get("semrush", "")
    if not api_key:
        log.error("SEMRUSH_API_KEY not set and no fallback in API_KEYS. Aborting.")
        return 2

    database = os.environ.get("SEMRUSH_DB", "au").lower()
    log.info("Generating secondary keywords via SEMrush (db=%s, anchors=%d/industry)",
             database, ANCHORS_PER_INDUSTRY)

    excluded = _primary_phrase_universe(INDUSTRY_KEYWORDS)
    log.info("Primary phrase universe (to exclude): %d phrases", len(excluded))

    semrush = SemrushClient(api_key)
    semrush._counter = {}  # reset run counter

    result: Dict[str, List[str]] = {}
    stats: Dict[str, Dict[str, int]] = {}

    for i, (industry, primary_kws) in enumerate(INDUSTRY_KEYWORDS.items(), start=1):
        log.info("[%d/%d] %s", i, len(INDUSTRY_KEYWORDS), industry)
        anchors = primary_kws[:ANCHORS_PER_INDUSTRY]
        picked = _fetch_one_industry(industry, anchors, semrush, database, excluded)
        result[industry] = [kw for kw, _, _ in picked]
        stats[industry] = {"kept": len(picked), "raw": -1}   # raw count captured via logs
        log.info("   → kept %d", len(picked))

    # Write file
    out_path = Path(__file__).resolve().parent / "secondary_keywords.py"
    text = _render_output(result, database, stats)
    out_path.write_text(text, encoding="utf-8")

    total = sum(len(v) for v in result.values())
    api_calls = semrush._counter.get("semrush", 0)
    log.info("Wrote %s — %d keywords across %d industries (%d SEMrush calls)",
             out_path.name, total, len(result), api_calls)

    # Also emit a small metadata JSON for ops/debug
    meta = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "database": database,
        "industries": len(result),
        "total_keywords": total,
        "semrush_api_calls": api_calls,
        "min_cpc": MIN_CPC,
        "min_volume": MIN_VOLUME,
    }
    (out_path.parent / "secondary_keywords_meta.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
